name: Deployment Pipeline

on:
  push:
    branches: [ main ]

jobs:
  skip_reduncy:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  test:
    runs-on: ubuntu-18.04
    env:
      # Django vars
      SSL_REQUIRED: 0
      DATABASE_URL: postgres://postgres:admin@db:5432/squadmakers_test
      ENGINE: django.db.backends.postgresql_psycopg2
      SECRET_KEY: YOURK_KEY
      DEBUG: 0
      ALLOWED_HOSTS: localhost 127.0.0.1 [::1]
      TIME_ZONE: America/Guayaquil
      # Postgres vars docker
      POSTGRES_DB: squadmakers_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      HOST: db
      PORT: 5432
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v3
        with:
          cache: "pip"
          python-version: 3.7
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          pytest
